AllCops:
  NewCops: enable
  Exclude:
    - bin/*

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Metrics/BlockLength:
  Exclude:
    - spec/controllers/shortened_urls_controller_spec.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/NumericLiterals:
  Exclude:
    - db/schema.rb
