AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - vendor/**/**
    - gemfiles/vendor/bundle/**/*

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/**

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/NumericLiterals:
  Exclude:
    - db/schema.rb
