#!/bin/bash
set -ex

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $POSTGRES_RO_USER WITH PASSWORD '$POSTGRES_RO_USER_PASSWORD';
	GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_RO_USER;
	GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO $POSTGRES_RO_USER;
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO $POSTGRES_RO_USER;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $POSTGRES_RO_USER;
EOSQL
