default: &default
  adapter: postgresql
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

primary: &primary
  <<: *default
  user: <%= ENV.fetch("POSTGRES_USER") { 'shorter' } %>
  password: <%= ENV.fetch("POSTGRES_password") { 'shorter_password' } %>
primary_replica: &primary_replica
  <<: *default
  user: <%= ENV.fetch("POSTGRES_RO_USER") { 'shorter_ro' } %>
  password: <%= ENV.fetch("POSTGRES_RO_USER_PASSWORD") { 'shorter_ro_password' } %>
  replica: true

development:
  primary:
    <<: *primary
    database: shorter
  primary_replica:
    <<: *primary_replica
    database: shorter

test:
  primary:
    <<: *primary
    database: shorter_test
  primary_replica:
    <<: *primary_replica
    database: shorter_test

production:
  primary:
    <<: *primary
    database: shorter_production
  primary_replica:
    <<: *primary_replica
    database: shorter_production
