default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

primary: &primary
  <<: *default
  user: <%= Rails.application.credentials.dig(:postgresql, :primary, :user) %>
  password: <%= Rails.application.credentials.dig(:postgresql, :primary, :password)  %>
primary_replica: &primary_replica
  <<: *default
  user: <%= Rails.application.credentials.dig(:postgresql, :primary_replica, :user) %>
  password: <%= Rails.application.credentials.dig(:postgresql, :primary_replica, :password)  %>
  replica: true

development:
  primary:
    <<: *primary
    database: shorter_development
  primary_replica:
    <<: *primary_replica
    database: shorter_development

test:
  primary:
    <<: *primary
    database: shorter_test
  primary_replica:
    <<: *primary_replica
    database: shorter_test

production:
  primary:
    <<: *primary
    database: shorter_production
  primary_replica:
    <<: *primary_replica
    database: shorter_production
