default: &default
  host: <%= ENV.fetch("REDIS_HOST") { 'redis' } %>
  port: <%= ENV.fetch("REDIS_PORT") { 6379 } %>
  db: 1
  timeout: 5
  connect_timeout: 5
  password: <%= ENV.fetch("REDIS_PASSWORD") { Rails.application.credentials.dig(:redis, :password) } %>

development:
  <<: *default

test:
  <<: *default
  db: 15

staging:
  <<: *default

production:
  <<: *default
