default: &default
  host: <%= Rails.application.credentials.redis.host %>
  port: <%= Rails.application.credentials.redis.port %>
  db: 1
  timeout: 5
  connect_timeout: 5
  password: <%= Rails.application.credentials.redis.port %>

development:
  <<: *default

test:
  <<: *default
  db: 15

staging:
  <<: *default

production:
  <<: *default
